name: 'RELEASE: Run cross-platform tests'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - stable

jobs:
  just_tests:
    name: ${{ matrix.os }} python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.py }}-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ !github.event.pull_request.draft && !contains(toJson(github.event), '[skip ci]') }}
    strategy:
      matrix:
        os: ['windows-latest', 'macos-latest']
        py: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Check out repo
      uses: actions/checkout@v6

    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.py }}
        cache: 'pip'
        cache-dependency-path: requirements-ci.txt

    - name: Update pip & setuptools
      run: python -m pip install -U pip setuptools

    - name: Install & report CI dependencies
      run: |
        python -m pip install -U --force-reinstall -r requirements-ci.txt
        python --version
        pip list

    - name: Run tests
      run: |
        pytest --cov
        tox -e sdist_install
